export const galleryImageAssets = [
  { src: "/yumeiho/yumeiho2.webp", alt: "Юмейхо терапия - мобилизация на гръбначния стълб", caption: "Юмейхо техники" },
  { src: "/team/hero.webp", alt: "Екипът на ТеКрего Русе", caption: "Нашият Екип" },
  { src: "/massage/massage.webp", alt: "Релаксиращ масаж в кабинет ТеКрего Русе", caption: "Релаксиращ масаж" },
  { src: "/bioresonance/biophilia2.webp", alt: "Биорезонансен анализ на организма", caption: "Биорезонансен анализ" },
  { src: "/certificates/certs.webp", alt: "Сертификати и дипломи на екипа на ТеКрего", caption: "Част от нашите сертификати" },
  { src: "/massage/honey.webp", alt: "Медена терапия в кабинет ТеКрего", caption: "Медена терапия" },
  { src: "/massage/massage2.webp", alt: "Масажна терапия за гръб и кръст в ТеКрего", caption: "Масажна терапия" },
  { src: "/yumeiho/yumeiho.webp", alt: "Юмейхо терапия - балансиране на таза", caption: "Юмейхо терапия" },
  { src: "/yumeiho/yumeiho3.webp", alt: "Юмейхо терапия - акупресура и енергийна работа", caption: "Акупресура" },
  { src: "/massage/massage3.webp", alt: "Професионален масаж в ТеКрего Русе", caption: "Професионален масаж" },
  { src: "/bioresonance/boiphilia.webp", alt: "Биорезонансна диагностика с апарат Biophilia", caption: "Биорезонансна диагностика" },
  { src: "/massage/massage4.webp", alt: "Релаксираща обстановка в ТеКрего", caption: "Релаксираща обстановка" },
  { src: "/enterance.webp", alt: "Вход на кабинет ТеКрего в Русе", caption: "Вход в кабинета" },
  { src: "/yumeiho/yumeiho4.webp", alt: "Юмейхо терапия ", caption: "Юмейхо техники на лице" },
  { src: "/yumeiho/yumeiho5.webp", alt: "Юмейхо терапия сеанс", caption: "Юмейхо сеанс" },
  { src: "/certificates/cert2.webp", alt: "Професионална квалификация масажист", caption: "Квалификация" },
  { src: "/certificates/cert1.webp", alt: "Сертификат по козметичен масаж", caption: "Козметичен Масаж - Сертификат" },
];
